import HomePage from '@/pages/Home';
import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Instagram clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <HomePage />
            </main>
        </>
    );
}
